feat: Added audience param to oauth request body (optional)
Aiven-Open/http-connector-for-apache-kafka pull request #157
Opened 2023-04-11 16:13 UTC by davidvanwyk

Often OAuth IDPs require an audience parameter to exist in the body of the client credentials flow (eg. Auth0). This makes this possible.

2023-04-11 16:16 UTC, davidvanwyk commented
Unsure if this requires anything additional to be added, but I have done some testing locally and this seems to work as expected and simply adds `&audience={audience_param}` to the body.

2023-07-05 08:09 UTC, jeqo requested changes
@davidvanwyk thanks for this PR.

Do we know of any other provider implementing this field apart from [Auth0](https://auth0.com/docs/secure/tokens/access-tokens/get-access-tokens)?  Looking for some reference, as seems to not be backed by a standard (some refer to this draft RFC: https://datatracker.ietf.org/doc/html/draft-tschofenig-oauth-audience-00 here https://stackoverflow.com/questions/45876960/how-to-specify-audience-for-an-oauth2-access-token)
Though, Auth0 may be enough providers to adopt this :)

About changes proposed, seems sensible to follow the same approach as scope which is also optional. If we agree that this field is a common one, I'd be happy with this implementation. Left some minor comments.

2023-07-05 08:09 UTC, jeqo commented on gradle.properties
> +version=0.7.1-SNAPSHOT
maybe not related to this change?

2023-07-05 08:09 UTC, jeqo commented on src/main/java/io/aiven/kafka/connect/http/sender/AccessTokenHttpRequestBuilder.java
> +        if (config.oauth2ClientAudience() != null) {
Could we add tests covering this new field?

2026-01-22 10:26 UTC, closed without merging